### ISSUE TITLE
Trying to fix "The WebAdministration module is required to use this function" on Server 2016

### ISSUE THREAD

**Issue by snblackout** [rmbolger/Posh-ACME.Deploy#14]
Hello there, 

I've been trying to get this working for a while.  I usually give up after renewing my domains and wait until expiration is going to happen again to try something else.  I know, my fault, I should probably spin up a 2016 VM and try on POSH-ACME test environment, but before that, I want to get some guidance from the actual repo admins for some directions I can take.

But this is what I get when renewing via Powershell command line with this command: 

`Submit-Renewal -MainDomain 'api.example.com' -Verbose | Set-IISCertificate -SiteName "api.example.com" -HostHeader "api.example.com" -RemoveOldCert -Verbose`

```
Exception: C:\Users\Administrator\Documents\PowerShell\Modules\Posh-ACME.Deploy\1.3.0\Public\Set-IISCertificate.ps1:23
Line |
  23 |              throw "The WebAdministration module is required to use th …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The WebAdministration module is required to use this function.
```

The certificate renews just fine after DNS propagation wait.

I've already installed IIS Server and all IIS Management Tools roles and rebooted the server.

I've done this command "Get-WindowsOptionalFeature -Online -FeatureName IIS-ManagementScriptingTools" I've read should be done.

I'm at a loss and just don't know where to turn to next.  I'm not a Powershell guru either.  I really want my scripts automated for certificate renewals and getting frustrated.  By comparison (and vent frustration), I've setup a handful of LAMP servers and setup Let's Encrypt automatic renewals with easier configuration :)

Thanks in advance.

**Comment by rmbolger** [comment]
Hey @snblackout, sorry to hear you're having trouble. Quick question while I go try and reproduce this on a test machine, are you running this from the built-in PowerShell 5.1 or the newer PowerShell 6 or 7? The WebAdministration module doesn't actually work unless you're using PowerShell 5.1. You can check what version you're in by running `$PSVersionTable.PSVersion` from within the session.

If you need/want to use PowerShell 7, there's a newer function you can use called `Set-IISCertificateNew` that relies on the more recent `IISAdministration` module rather than the old `WebAdministration` module. The catch is that you need the newer 1.1.0.0 version of that module from PSGallery. More info [here](https://blogs.iis.net/iisteam/introducing-iisadministration-in-the-powershell-gallery).

**Comment by snblackout** [comment]
Hi @rmbolger, thanks for your quick response!

I am actually using `Powershell 7` for these commands after running that command.  Also, when I've tried testing in `Task Scheduler`, I point to `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe` with the script file as parameter.  But since it clearly shows `v1.0`, is it safe to assume that's trying to run the script in `Powershell Version 1`?? 😂

Anyway, the Powershell version thing could be the issue all along.  Let me do some more testing on my end when I get some time, potentially in a 2016 VM on a test environment with the new `Set-IISCertificateNew`

To be honest, the Powershellf versions is confusing in itself for a novice 😆

Thanks again.

**Comment by rmbolger** [comment]
I hear you on the version confusion. Don't feel bad, even PowerShell people get confused about it on occasion. There was a big engine revamp in the move from PowerShell 5 to 6 in order to make it cross-platform. PowerShell 5.1 is the last version of what is officially known as "**Windows** PowerShell" and has an executable called `powershell.exe` (just ignore the 1.0 folder name). All versions beyond 5 are now known simply as "PowerShell" and have an executable called `pwsh.exe` (which is usually somewhere in `C:\Program Files`).

So ironically, if your scheduled task was been pointing to `powershell.exe`, it should have worked and we can try and figure out what went wrong if we can get some logs. Switching to `Set-IISCertificateNew` should also work from both `powershell.exe` and `pwsh.exe` as long as you've got the updated version of the module installed.

```powershell
Install-Module IISAdministration -Scope AllUsers -Force
```
