### ISSUE TITLE
Need some help on creating a renewal script that renews wildcard certificates bound to multiple websites

### ISSUE THREAD

**Issue by stevenvolckaert** [rmbolger/Posh-ACME.Deploy#15]
I'm attempting to create a submit renewal PowerShell script that I'll trigger with Windows Task Scheduler, two times per day at random times.

It will look something like this:

``` PowerShell
Submit-Renewal -AllOrders | ForEach-Object {
    $paCertificate = $_;
    $paCertificate | Format-List;
    # TODO Need to get all IIS websites, read all their bindings; do they use an old cert that matches one of the SANs of $paCertificate?
}
```

The server where I will be running this task, has a number of IIS websites (currently around 15), and new ones are added regularly. At the moment, all IIS websites use the same `*.mydomain.com` wildcard certificate for HTTPS, but we'll add some new ones soon that use specific, non-wildcard certificate (e.g. `foobar.mydomain.com`).

I need a script (or, if a single script is impossible, perhaps multiple ones) that renews all certs and updates the bindings of all IIS sites.

I'm having trouble figuring out how to do this with the `Set-IISCertificate` cmdlet from the `Posh-ACME.Deploy` module, because it requires the `-SiteName` parameter.

If I could somehow retrieve the names of all current websites that have an HTTPS binding using the **old** `*.mydomain.com` cert, I could loop over the websites and call `Set-IISCertificate -SiteName $SiteName -RemoveOldCert` in every iteration.

How can I reliably find all IIS websites on a server that use a HTTPS binding using the **old** `*.mydomain.com` cert?

Perhaps I need to search for the old certificate's thumbprint like this?

``` PowerShell
$OldCertificateThumbprint = Get-ChildItem Cert:\LocalMachine\My\ | Where-Object { $_.Subject -Contains "CN=*.mydomain.com" } | Select-Object Thumbprint
```

And then find all sites with

``` PowerShell
Get-ChildItem IIS:\SslBindings\ | ?{$_.thumbprint -eq $OldCertificateThumbprint }
```

This requires the use of the `WebAdministration` module however, which seems to be not recommended; I've read that Microsoft recommends using the `IISAdministration` instead.

Perhaps anyone knows how this should be done with the `IISAdministration` module?

Many thanks in advance for your help!

**Comment by rmbolger** [comment]
If you're on IIS 8.5 (Windows Server 2012 R2) or newer, you might be able to avoid enumerating the sites entirely using an underlying component of the [Certificate Rebind](https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-85/certificate-rebind-in-iis85) feature. The way it works normally is only via native Windows certificate auto-enrollment. But all it's really doing is creating a scheduled task that triggers on a specific event log message and then runs a command with the old and new cert thumbprints like this:

```powershell
& $env:SystemRoot\system32\inetsrv\appcmd.exe renew binding /oldcert:THUMBPRINT /newcert:THUMBPRINT
```

That will automatically update all IIS bindings that currently reference the cert with the old thumbprint to the cert with the new thumbprint. So all your script has to be able to do is find the old thumbprint like in your `Get-ChildItem Cert:\blah` example and grab the new one from the cert object returned by Submit-Renewal.

Another solution that would probably work is switching the sites to use the Centralized Certificate Store (CCS). I haven't used it much, but it's a little more tedious because you have to create copies of the resulting PFX files for every SAN name in the cert. However once you do, overwriting the old copies with the new copies is all that's needed if I understand how things work correctly.

**Comment by rmbolger** [comment]
So I've been meaning to mess with this rebinding feature for a while and this is the perfect excuse. Give this script a try and see how it goes for you. It assumes all of your certs are associated with the same account and that account and server are currently active. You'd have to add some additional logic if the cert orders are spread between accounts or ACME servers. It also assumes all cert orders are associated with an IIS site that ultimately needs a rebind. But the `appcmd.exe` line doesn't seem to care whether there are valid bindings associated with the thumbprints you send it or not. Even with thumbprints like `asdf` and `qwer`, it doesn't throw an error.

```powershell
#Requires -Modules Posh-ACME

[CmdletBinding()]
param(
    [switch]$RemoveOldCerts,
    [switch]$Force
)

Get-PAOrder -List | ForEach-Object {

    # grab the current cert thumbprint if it exists
    $oldThumb = $_ | Get-PACertificate | Select -Expand Thumbprint

    # try to renew
    $orderName = $_.Name
    $newCert = $_ | Submit-Renewal -Force:$Force

    if ($newCert) {

        $newThumb = $newCert.Thumbprint

        # make sure it's installed
        if (-not (Get-Item Cert:\LocalMachine\My\$newThumb -EA Ignore)) {
            Write-Verbose "Importing updated '$orderName' cert to LocalMachine\My. Thumbprint: $newThumb"
            $newCert | Install-PACertificate
        }

        # update the bindings if we have a corresponding old thumbprint
        if ($oldThumb) {
            Write-Verbose "Updating bindings for '$orderName' cert: $oldThumb -> $newThumb"
            & $env:SystemRoot\system32\inetsrv\appcmd.exe renew binding /oldcert:$oldThumb /newcert:$newThumb

            # remove the old cert if asked
            if ($RemoveOldCerts) {
                $oldCert = Get-ChildItem Cert:\LocalMachine\My | Where-Object {$_.Thumbprint -eq $oldThumb}
                if ($oldCert) {
                    Write-Verbose "Deleting old certificate with thumbprint $oldThumb"
                    $oldCert | Remove-Item
                }
            }
        }
        else {
            Write-Warning "Unable to update bindings for '$($newCert.Name)' cert. No old thumbprint found."
        }
    }
}
```

**Comment by stevenvolckaert** [comment]
@rmbolger Thank you very much for your help! I'll try your script out today or tomorrow. I'll report back here with my findings after that 👌
