### ISSUE TITLE
Executing remote commands using Invoke-Command or Enter-PSSession produces errors

### ISSUE THREAD

**Issue by tmr-cf** [rmbolger/Posh-ACME.Deploy#17]
Here is a use case where one server is renewing a wildcard certificate with Let's Encrypt but that certificate has to be redeployed quarterly to many other servers.

Posh-ACME.Deploy is installed on multiple servers using:

`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`
`Install-Module PowerShellGet -RequiredVersion 2.2.4 -SkipPublisherCheck -Force`
`iex (irm https://raw.githubusercontent.com/rmbolger/Posh-ACME.Deploy/main/instdev.ps1)`

One SERVER maintains the PAOrder and exports renewed certificate to PFX file:

`$domainName = 'mydomain.com'`
`Set-PAOrder $domainName`
`if ($cert = Submit-Renewal) {`
`$cert | Set-IISCertificate -SiteName 'Default Web Site' -RemoveOldCert`
`$certPath = 'cert:\localMachine\my\' + $cert.Thumbprint`
`$mypwd = ConvertTo-SecureString -String 'p@ssWord' -Force -AsPlainText`
`Get-ChildItem -Path $certPath | Export-PfxCertificate -FilePath \\SERVER\share\certpfx.pfx -Password $mypwd -Force`
`}`

Another server (WEBSERVER) is to import PFX certificate and Set-IISCertificate:

`$remoteCommands = {`
`$mypwd = ConvertTo-SecureString -String 'p@ssWord' -Force -AsPlainText`
`Set-IISCertificate -PfxFile '\\SERVER\share\certpfx.pfx' -PfxPass $mypwd -SiteName 'Default Web Site' -Port 443 -RemoveOldCert`
`}`
`Invoke-Command -ComputerName WEBSERVER -ScriptBlock $remoteCommands`
 
Produces this error:

![image](https://user-images.githubusercontent.com/83948515/143534743-bfcbbaea-2228-4798-94e9-04cdc1ffb3f3.png)

However, no error when commands are executed locally on WEBSERVER in PowerShell console:

Example:

`$mypwd = ConvertTo-SecureString -String 'p@ssWord' -Force -AsPlainText`
`Set-IISCertificate -PfxFile '\\SERVER\share\certpfx.pfx' -PfxPass $mypwd -SiteName 'Default Web Site' -Port 443 -RemoveOldCert`

![image](https://user-images.githubusercontent.com/83948515/143540042-91752fcb-79ba-408c-990d-f7042cd696c2.png)

**Comment by rmbolger** [comment]
Hi there @tmr-cf. I believe the issue you're running into is what is known as the "double hop" problem. Essentially, the implicit credentials being used to Invoke-Command on `WEBSERVER` aren't able to be passed to `\\SERVER`, thus the access denied error. When you launch the same command locally, `\\SERVER` is now the second server instead of the third and you no longer have the problem.

Here's a Microsoft doc article on the problem and various ways to work around it.
https://docs.microsoft.com/en-us/powershell/scripting/learn/remoting/ps-remoting-second-hop

However, have you considered using the [Centralized Cert Store](https://docs.microsoft.com/en-us/iis/get-started/whats-new-in-iis-8/iis-80-centralized-ssl-certificate-support-ssl-scalability-and-manageability) feature that was introduced in IIS 8? It's tailor made for your situation and it sounds like you've already got the share ready to go. Basically each server's binding is configured to get the cert directly from the share and when the files on the share get updated, they all start using the new version. No need to hassle with importing the PFX on each machine.

I've actually been meaning to add a Posh-ACME.Deploy function to help with the distribution because the only tricky part is each SAN you're using needs its own copy of the file.
