### ISSUE TITLE
Enhancement to Set-IISCertificateNew to handle multiple bindings in a single call

### ISSUE THREAD

**Issue by inzi** [rmbolger/Posh-ACME.Deploy#23]
I have added an enhancement to Set-IISCertificateNew to allow binding a certificate to multiple host headers in a single call.

# Solves
*.example.com doesn't respond to https://example.com, and example.com doesn't respond to https://www.example.com
Two separate calls are required to update both bindings.

# Allow for multiple host headers

If DNS has an A record pointing at example.com (@ -> example.com's IP)
and another A record for record.example.com (record -> example.com's IP)

IIS needs two separate bindings for for the site (one for example.com and one for *.example.com)

This enhancement allows multiple host headers, comma separated, to be used without a breaking change (so far in my testing).
This can be used rather than two separate calls.

I'm not a contributor, so I can't do a PR, so I've attached my enhanced Set-IISCertifiicateNew here.
[Set-IISCertificateNew.ps1.txt](https://github.com/rmbolger/Posh-ACME.Deploy/files/8767831/Set-IISCertificateNew.ps1.txt)

# Example Implementations:
Single Host Header

Set-IISCertificateNew -SiteName $siteName -Port 443 -HostHeader "example.com" -RequireSNI -Verbose -ErrorAction Stop 

Multiple Host Headers

Set-IISCertificateNew -SiteName $siteName -Port 443 -HostHeader "example.com,*.example.com" -RequireSNI -Verbose -ErrorAction Stop 

Hope this helps someone, Cheers. 

Oh, and note to self, if you have computer management open, it locks the applicationHost.config file, too.

**Comment by rmbolger** [comment]
Hey @inzi, thanks for the great idea! I tweaked your implementation just a bit so that `-HostHeader` accepts a string array instead of a single string which shouldn't be a breaking change. It makes things slightly easier by avoiding the string splitting. I also moved the code that removes old certs out of the host header loop so it doesn't try to delete the same old cert multiple times. I should have the changes committed to main shortly.

P.S. For future reference, there's no contributor role that you need to be a part of in order to submit a PR. From what I understand, you automatically get labeled as a contributor the first time a PR is merged into the code base.

**Comment by inzi** [comment]
Hi Rmbolger, I was unable to make a new branch to do a PR from.

Maybe I just need to revisit how to do a PR without a branch in github.

**Comment by rmbolger** [comment]
You can't make a branch on the main project repo. You have to fork the project first, make your branch there (or not), and then submit the PR from your fork. I believe once the PR is submitted you can also delete your fork unless you want to keep it around.

**Comment by inzi** [comment]
Ok, will go that route next time. =)

Thanks!

**Comment by rmbolger** [comment]
This is now live in 1.6.0
