### ISSUE TITLE
Dependency issue

### ISSUE THREAD

**Issue by 100110010111** [rmbolger/Posh-ACME.Deploy#26]
I am running into an issue uwing powershell 7. This script seems to depend on having WebAdministration installed, but i cant seem to install it on powershell 7. What am I doing wrong and how can I work past this?

**Comment by rmbolger** [comment]
Hi @100110010111, thanks for reaching out. You're not doing anything wrong. The `Set-IISCertificate` function does indeed depend on the legacy `WebAdministration` module. But as you've found, it hasn't been updated to support PowerShell 7. There is also a different function called `Set-IISCertificateNew` that changes the dependency to the newer `IISAdministration` module. It also technically hasn't been updated to support PowerShell 7, but it seems to work well enough via implicit remoting which is what the function does if it detects it's running in PS 6+.

So give this a try. Make sure you have at least the `1.1.0.0` version of the module installed from PS Gallery:

```
Install-Module IISAdministration -MinimumVersion 1.1.0.0
```

Then in your Posh-ACME script, use the `Set-IISCertificateNew` function instead of `Set-IISCertificate`.
