### ISSUE TITLE
Set-IISCertificate - RequireSNI Switch Refactor

### ISSUE THREAD

**Issue by jamesaepp** [rmbolger/Posh-ACME.Deploy#27]
Greetings,

I've been working with both Posh-ACME modules recently on a project. One thing I noticed is the below (on Windows Server 2019).

From my review of the function, it appears that it's making the assumption that the only thing the sslFlags int is used for is SNI, but I don't think this is true. From my own testing, I think it's a set of boolean values which is then formatted into an integer. See below screenshot, I think it gives the general idea.

![image](https://github.com/rmbolger/Posh-ACME.Deploy/assets/6477969/d4939aa4-820d-4111-a28e-f8abc7d86b4e)

Say you had an existing site binding with all three checkboxes selected - you'd get a value of decimal 13 (8+4+1). Then say you ran the function. If my reading of the function is correct, the combination of the logic on lines 53, 54, 70, (and maybe?) 158 would break your configuration and only leave the SNI option selected (or deselected), and all other options would become disabled.

I haven't explicitly tested this (yet) but came across it in my review as I build out my own project. I think a much better way to handle this would be some kind of handling with a boolean such as:

`[boolean]$SNI = ((Get-WebBinding -Name $SiteName -Protocol 'https' | Where-Object {$_.bindingInformation -eq $bindMatch}).sslFlags -band 1)`

Then of course, you'd have to refactor the function so that this new way of processing the RequireSNI switch is handled correctly, and not overwrite any other sslFlags. The point is, the input given by the user of the function is not always the same as the output/result of what the function does.

**Comment by rmbolger** [comment]
Thanks for bringing this up, @jamesaepp. My memory is hazy, but it's quite possible I wrote this originally against an IIS version that didn't have those other options yet. Definitely seems like it could use a refactor.

**Comment by rmbolger** [comment]
I've decided to deprecate the `Set-IISCertificate` function in favor of the newer `Set-IISCertificateNew` function and refactored the latter to support all of the new SSL binding flags in the most recent version of IIS on Windows Server 2022. As part of the change, I also decided to rename `Set-IISCertificate` to `Set-IISCertificateOld` and `Set-IISCertificateNew` to `Set-IISCertificate` which will end up as a 2.0 breaking change release when it goes live. Though I've got a few more things I need to do before that happens. 

The updated `Set-IISCertificate(New)` function also shouldn't clobber existing binding flags even if new ones are added that the module doesn't know about yet. Essentially, whatever flags you specify (true or false) will be reflected in the binding, but anything you don't specify will be left as-is.

If you have some time, please try it out. Just remember that it requires the [IISAdministration module](https://www.powershellgallery.com/packages/IISAdministration/) version 1.1.0.0 or newer  instead of the older WebAdministration module.

**Comment by jamesaepp** [comment]
Sorry to leave you hanging on this. I'm not confident I can dedicate time to testing this out unfortunately, so in case you were - don't count/wait on me to give you good, quality feedback here (until 2.0 that is 😉).

Thanks for all the hard work put into this project alive and maintained.

**Comment by rmbolger** [comment]
No worries. I've been stalled on working on hobby stuff lately anyway.

**Comment by fthobe** [comment]
> I've decided to deprecate the `Set-IISCertificate` function in favor of the newer `Set-IISCertificateNew` function and refactored the latter to support all of the new SSL binding flags in the most recent version of IIS on Windows Server 2022. As part of the change, I also decided to rename `Set-IISCertificate` to `Set-IISCertificateOld` and `Set-IISCertificateNew` to `Set-IISCertificate` which will end up as a 2.0 breaking change release when it goes live. Though I've got a few more things I need to do before that happens.
> 
> The updated `Set-IISCertificate(New)` function also shouldn't clobber existing binding flags even if new ones are added that the module doesn't know about yet. Essentially, whatever flags you specify (true or false) will be reflected in the binding, but anything you don't specify will be left as-is.
> 
> If you have some time, please try it out. Just remember that it requires the [IISAdministration module](https://www.powershellgallery.com/packages/IISAdministration/) version 1.1.0.0 or newer instead of the older WebAdministration module.

Is this still an issue to be tested?

**Comment by rmbolger** [comment]
Yes and more eyes are welcome. But you'll have to use the dev version via the instructions in the readme. No promises on when it will go live though.

**Comment by rmbolger** [comment]
This is now live in v2.0.0
