### ISSUE TITLE
Set-IISCertificate Shall Update Existing Binding on Port 443 Instead of Creating A New One

### ISSUE THREAD

**Issue by Aster-the-Med-Stu** [rmbolger/Posh-ACME.Deploy#4]
After running Set-IISCertificate on a test server, I found that a new binding without SNI is created. This is a little annoying as SNI is needed for servers running multiple SSL sites. I think that Posh-ACME.Deploy shall update binding with SNI first if one exists.

![Binding on 443 without SNI](https://user-images.githubusercontent.com/32929636/67627662-02101480-f893-11e9-9911-7725247bbf55.png)

Besides, is it possible to delete out-dated certificate at the same time? As the certificates are sharing the same certificate holder name, manually updating certificates is a pain. I have to check out certificates' properties to figure out which one is the newest one.

![Which is which...](https://user-images.githubusercontent.com/32929636/67627741-67183a00-f894-11e9-94d0-0a423e4c69e2.png)

**Comment by rmbolger** [comment]
Hi @Aster-the-Med-Stu. Thanks for your interest. Sorry for the relative lack of polish on this module so far.

It sounds like you should be using the `-HostHeader` and `-RequireSNI` parameters with the function in order to apply the cert to your existing site. Additionally, there's a `-RemoveOldCert` parameter which should delete the previous certificate from the Windows cert store after it sets up the new one.
