### ISSUE TITLE
WSMAN RDP

### ISSUE THREAD

**Issue by mikes-gh** [rmbolger/Posh-ACME.Deploy#5]
Love the idea of deploy module.

I use this for RDP (not RDS server) and WSMAN

```
$cert = Submit-Renewal
if ($cert) {
    Set-WSManInstance -ResourceUri winrm/config/Listener -SelectorSet @{Address="*";Transport="HTTPS"} -ValueSet @{CertificateThumbprint=$cert.ThumbPrint}
    Set-CimInstance -Namespace "root\cimv2\TerminalServices" -Query "SELECT * FROM Win32_TSGeneralSetting WHERE TerminalName = ''RDP-Tcp''" -Property @{ SSLCertificateSHA1Hash = $cert.Thumbprint }
}
```

Any interest in this

edit I think RDP is same as RDSH

**Comment by rmbolger** [comment]
Yeah, RDP (Remote Desktop Protocol) is the name of the protocol, RDSH (Remote Desktop Session Host) is the name of the service. And so the existing `Set-RDSHCertificate` would take care of that. It's using `Set-WmiInstance` rather than `Set-CimInstance` but should be functionally the same

Having a function for WSMAN would be cool too though.

**Comment by mikes-gh** [comment]
Set-CimInstance is preferable for PScore.

**Comment by rmbolger** [comment]
Indeed

**Comment by mikes-gh** [comment]
Yeh bit of a nit sorry.  Your libraries are great and I don't know how you make time for it all. 
I should be making contributions rather than suggestions but hopefully they are useful suggestions.
I see a situation quite soon where we will be using powershell core on windows as default even with windows specific modules.

**Comment by rmbolger** [comment]
It's all good. I'm always open to suggestions. I didn't even realize the CIM cmdlets had been around since 3.0. I also feel bad that this deploy module hasn't even had a real release yet.
