### ISSUE TITLE
IIS Binding Help

### ISSUE THREAD

**Issue by mclacore** [rmbolger/Posh-ACME.Deploy#9]
This is just a general question: using Posh-ACME.Deploy, how would you approach writing a script to automate the process of adding a new binding to an IIS site? We would then proceed with requesting the SSL cert from Let's Encrypt, then binding the cert to the new hostname.

**Comment by rmbolger** [comment]
Hi @mclacore. Thanks for the question.

I'm not sure if IIS will let you create an https binding until you have a cert to use with it (even an invalid or self-signed one). So getting the cert is usually the first step.

Once you have the cert, the `Set-IISCertificate` function in this module will take care of creating the binding if it doesn't already exist and associating the cert with it. The Quick Start section of the readme on the project homepage has a couple basic examples that should be most of what you need. There are some additional parameters you can use for things like configuring host headers, SNI, and custom ports as well.

**Comment by mclacore** [comment]
Thank you for the quick reply!

Do you have a reference sheet for which parameters work with your cmdlets?

**Comment by rmbolger** [comment]
I don't have anything published on the web for them. But each function is documented using the native PowerShell help system. So you can do something like this:

```powershell
Get-Help Set-IISCertificate -Full
```

I should probably add that most of the functions in this module are designed to be used with the "PACertificate" objects output by the main Posh-ACME module. So if you pipe a PACertificate object to the function, you won't have to explicitly specify the parameters like `CertThumbprint`, `PfxFile`, and `PfxPass` because they'll be picked up automatically from the piped object.
